language: c
sudo: false # only for faster builds
script:
  - make

env:
  global:
     - CODECOV_TOKEN=:c3027d64-e198-4cd2-8c96-9206b420f6c7

after_success:
  - bash <(curl -s https://codecov.io/bash)
